### ISSUE TITLE
Find a way to differentiate types of issues

### ISSUE THREAD

**Issue by menor** [resmio/git-along#1]
Right now I can think of:
- Tasks: Just one item that it's actionable (the action to take to move it forward is clear)
- Projects: Issues that comprise several actionable tasks, the tasks can already be defined or can be added later. Issues in projects should also be actionable on themselves.
- Discussions: Online discussions about how to solve a particular situation (API behaviour, how o handle errors globally... ) they can be summarised later and put into a wiki article or readme in this same repo.

This would be a discussion issue ;) so please if you can think of new types, say it here.

**Comment by jessicalins** [comment]
New types that I can think now is that we have some issues that are more related to the product itself - one new feature, bug fix - and another ones more 'technical' - the ones that are about performance, refactoring, and so on. These 2 types would be like subdivisions from the Task type :)

**Comment by ihucos** [comment]
Agree

**Comment by ihucos** [comment]
We could also have something like examine/investigation/inspection/planning where its more about planning and researching than actual programming.

**Comment by menor** [comment]
The just in time added [github projects](https://help.github.com/articles/tracking-the-progress-of-your-work-with-projects/) proves that we weren't the ones with the same problem. So now we can use projects and tasks like this:

- **Task** One actionable item
- **Project** A feature comprised of several actionable tasks

Regarding the other suggestions (discussion, distinction between product and technical, investigation and planning) we can use tags. I'm closing this and opening an issue regarding tag names in #5
