### ISSUE TITLE
Define labels for category: Type

### ISSUE THREAD

**Issue by menor** [resmio/git-along#10]
Type labels are the ones that help to define what kind of issue we are dealing with
proposed color: SkyBlue (#87CEEB)
- `feature`: new features
- `enhancement`: improving an existing feature
- `refactor`:  Issues about paying technical debt
- `discussion`: Issues that are not actionable, just a place to discuss

proposed color: red (#FF0000)
- `bug 💩`
- `crash 🔥`

**Comment by JanNash** [comment]
- `crash 🔥` as opposed to a bahvioural `bug 💩`?  

I guess that's only for the iPad App?
Maybe also for Backend issues that lead to 5xx errors?

**Comment by JanNash** [comment]
Yay!

**Comment by JanNash** [comment]
investigation 🔍

**Comment by menor** [comment]
great thanks, I would reserve the emojis for the most important types though, what do you think?

**Comment by JanNash** [comment]
Yeah , agreed, I tend to overuse them :D

**Comment by menor** [comment]
We all do 🙀
Can you provide a description for `investigation`?

**Comment by menor** [comment]
Putting this here for reference
![image](https://cloud.githubusercontent.com/assets/1360794/18634236/6815b568-7e80-11e6-825a-ef1f6ce643ff.png)

**Comment by JanNash** [comment]
Once we have all of them, should I try 'n' adapt one of the scripts that do the creation of labels automagically? (https://gist.github.com/JanNash/3d7aba4b9fcd78c930425f95d580da62)

**Comment by menor** [comment]
That'd be great, I just tried but 2 factor auth was being a pain in the ass

**Comment by JannKleen** [comment]
@menor you can actually create a token somewhere in the settings and use it instead of your pw, that's how you get around 2FA in this case...

Also we should remember that some of them should be renamed rather than deleting old tags and creating new ones
