### ISSUE TITLE
Define labels for category: Workflow

### ISSUE THREAD

**Issue by menor** [resmio/git-along#11]
Workflow labels define the position of an issue or PR in out process:

**Needs action labels** 
color: gold (#FFD700)
- `split into tasks`: Issue voted as a Project
- `discussion needed`: `Needs agreement on how to solve it`
- `review backend`
- `review frontend`
- `review product`

**Approved labels** 
color: pale green (#98FB98)
- `review backend 👍`
- `review frontend 👍`
- `review product 👍`

**Rejected labels** 
color: firebrick (#B22222)
- `review backend 👎`
- `review frontend 👎`
- `review product 👎`
- `blocked`: Depends on something else before it can be acted on.
- `needs gif`: On interface changes the PR should include a gif with the new behavior

**Situation labels**
color: whitesmoke (#F5F5F5)
- `on test`: It's on the test server
- `in progress`: Someone is working on it
- `sprint ready`: Ready to estimate

**Special Label**
color: forestGreen (#228B22)
- `ready for merge 🕶` : Title says it all

**Comment by menor** [comment]
@JannKleen Is it possible to have a `deployed` label for things that have been already deployed, that would make a lot easier to compile this data to communicate that to the rest of the company. Can it be automated?

**Comment by JanNash** [comment]
Also, is it possible to auto-set and unset a 'currently-on-test' label?

**Comment by JanNash** [comment]
`ready for deploy`, too?

**Comment by menor** [comment]
Do you need the `ready for deploy` @JannKleen @nsb ?
I guess you need it, right @JanNash ?

**Comment by menor** [comment]
![image](https://cloud.githubusercontent.com/assets/1360794/18634556/b29700a0-7e81-11e6-8da8-9cb4eb5a3f85.png)
![image](https://cloud.githubusercontent.com/assets/1360794/18634568/c2a395ee-7e81-11e6-83d7-1c5318a4db4f.png)

**Comment by JanNash** [comment]
No emoji @ all? 😞

**Comment by JanNash** [comment]
Yeah, not sure if I need the `ready to deploy` label. @JannKleen do you think we could benefit from that in the tables repo?

**Comment by menor** [comment]
They don't allow it @JanNash 😢 
This is clearly not targeted at millenials

**Comment by JanNash** [comment]
😭

**Comment by JannKleen** [comment]
@JanNash @menor i didn't find a ready-made solution to tag PRs once they're merged into master but feel free to come up with a script to do this.

We'd also be using the 'deployed' tags once for the weekly update email and once for the monday standup (the two times a week we need to report them).

Maybe there's a better way to do this

**Comment by menor** [comment]
We can filter by `is:pr is:merged` in the PR list, but I think having the tag is better since I guess that also shows PR that have been merged to a branch different from master.

What about putting the label manually after merging or deploying? That way we would be able to filter things that have been merged but not deployed and have a clear picture of the PRs we are deploying.

I know manually is not ideal, but we need to label everything else manually anyways.
