### ISSUE TITLE
Define labels for size and priority categories

### ISSUE THREAD

**Issue by menor** [resmio/git-along#12]
Size labels specify the estimated amount of time an issue is going to take to complete. Proposed color is #FF7F50 (Coral)

Labels:
- `x-small`:  You only need one cup of coffee to finish it
- `small`:  < ☕️☕️☕️  (3)
- `medium`: < ☕️☕️☕️☕️☕️  (5)
- `large`: < ☕️☕️☕️☕️☕️☕️☕️☕️☕️☕️  (10)
- `x-large`: Split it into a project with more manageable chunks

Priority labels can be assigned by product managers as long as they don't abuse them ;) Proposed color is #FF1493 (Deep Pink)

Labels: 
- `P1`: Critical, drop whatever you are working on and work on this.
- `P2`: Must. Must be finished this milestone.
- `P3`: Should. Should be finished this milestone.

**Comment by fabiennepimenta** [comment]
Sounds good.
But we are not splitting large issues anymore? Only x-large?  –  I kind of agree with that, sometimes is just large and we don't need to split it, but I'm not developing so I don't know :P

**Comment by JannKleen** [comment]
re: Labels
I like the idea of P1 and P2 (I think P3 would be the default priority in this case)

re: Sizes
Waffle offers the Fibonacci sequence as many others do as well (1, 2, 3, 5, 8, 13 points), some use a geometric sequence like (1, 2, 4, 8, 16, 32 points). 
We're currently using 1, 2, 5, 8, 13 points on waffle (so we skipped the 3).

The main point in all of these (and also in @menor 's suggestion) is to have exponential growth (because we're getting less accurate in judging complexity the bigger the tasks get). Also it's important not to link them with actual hours but keep them as an abstract measurement (which makes it easier to think about the complexity of the problem itself, rather than the time spent).

I'm fine with any of the point distributions, I'd just suggest to think about bringing back X-Large as well and adjusting our voting behaviour (but having an additional 'Split / req's needed' card would make sense in that case)

**Comment by menor** [comment]
I forgot about the large splitting @fabiennepimenta although I think that medium is too small to be the biggest issue, let's see what other developers think. About bringing back the x-large @JannKleen I like your idea of having a 'split' card for them, what if we call it 'Project' to keep things more consistent? everything larger than 'large' is would not be a task anymore but a 'project'

About the P3 you are right, since it's the default for the milestone I think we don't need it, the less labels the better

**Comment by heinburger** [comment]
I agree with all these points! I would like to see the range xs-xl come back to our voting scheme as well (honestly, we have been working on l/xl issues even though they have not been voted that way). Are these 'points' just something for us down the road? I'm not sure I understand this scoring. As another point, maybe we could figure out a better way to share these issue sizes among ourselves. like if you do one xl last sprint, this sprint you take some smaller ones or something (not sure if this needs to be a "rule", but more of a suggestion?)

**Comment by menor** [comment]
I'm OK with having a little chat with you at the beginning of the sprint and decide how to split the issues based on areas of knowledge/energy @heinburger I don't know if that will work, or you were thinking of something more elaborated?

To do this though, we need to make more clear when the sprint begins and end, and have all the issues for a sprint at the beginning of it (if not before)

**Comment by JanNash** [comment]
That sounds all very good, love the idea of a 'Project'-card @menor !I'd keep the Fibonacci point distribution.

**Comment by menor** [comment]
So that makes:
x-small: 1 coffee
small: 2
medium: 3
large: 5
x-large: 8

And then projects, right?

**Comment by JanNash** [comment]
I already asked myself if it would make sense to split the estimation meeting off of the normal sprint meeting flow. Something along the lines of 
Thursday: Estimation meeting
Friday: Sprint is compiled
Monday: Old Sprint ends / New Sprint starts
---
Thursday (1,5 weeks later): Estimation meeting
...

Also, we could maybe have ad-hoc estimations if there are important issues that we want to get into the next Sprint. I guess they should have more than one issue to estimate, so the estimates stay comparable...

**Comment by JanNash** [comment]
@menor Sorry, I misworded. I meant staying with the current point-distribution (Fibonacci with skipped 3)

**Comment by heinburger** [comment]
@jose - I'm not sure, but just a little more conversation (like you say) about which issues we are taking form the sprint might be cool

yeah - I think this point scheme is perfect - Yeah - @nash I like that very much

**Comment by menor** [comment]
I love the idea of having fixed sprint times @JanNash, I think it will help a lot. In the sprint meeting we could also first go through all the open PR, decide what's missing to close them and assign people to finish them with a priority tag to avoid 'rotten code'. Also if we decide a task it's a project, a person should be assigned right at that moment to split the project into tasks.

Also if we do it like that @heinburger we can have an unofficial chat on every two fridays at lunch time and decide there what to do.

**Comment by menor** [comment]
Copy the new point distribution from the PR discussion here:
```
x-small: 1 coffee
small: 3
medium: 5
large: 8
x-large: 13
```
I wouldn't bring back x-large but I will go with consensus.

**Comment by menor** [comment]
@JannKleen @mmarder what should we do with x-large?

**Comment by mmarder** [comment]
I would keep x-large but we should put the rule on us that those issues have to be split up.

**Comment by menor** [comment]
Ok, then will keep it, my concern is that we'll need to put two tags `x-large` and `split into tasks` every time we have an extra large. I was thinking we could vote something as `split into tasks` in the sprint meeting and in that same moment include the issue in the sprint and assign some person to split it up.

**Comment by fabiennepimenta** [comment]
What about a meeting for a 'review' sprint on the last friday of the sprint? 
And on Monday it starts the new one. 

This way we are ending the week and a sprint / we demo / show what we did in this sprint instead of doing this in the new sprint planing. 

 What do you think?

**Comment by menor** [comment]
For me the less meetings the better, I would do it in the sprint planning. But if most of the people prefer to do it this way I am also OK

**Comment by fabiennepimenta** [comment]
I understand that, but it would be also useful as 'retrospective' about the past sprint. Instead of making everything in the same meeting – that is exhausting.
