### ISSUE TITLE
Create a Sprint Calendar

### ISSUE THREAD

**Issue by menor** [resmio/git-along#29]
I loved [this idea](https://github.com/resmio/git-along/issues/12#issuecomment-247932042) from @JanNash so I put it up for discussion [here](https://github.com/resmio/git-along/issues/23) 

If that works what about putting our next 3 sprints in a calendar and reserve the days for code reviewing, issue picking, estimation meetings... ?

**Comment by JanNash** [comment]
I guess this was fixed by #38 ?

**Comment by menor** [comment]
You guessed well @JanNash
