### ISSUE TITLE
Create guidelines for pull request message

### ISSUE THREAD

**Issue by menor** [resmio/git-along#31]
Like a template, cause I know we all like templates and writing more than 1 line of text, we we like more to do code reviews without completely knowing what's going on.

**Comment by fabiennepimenta** [comment]
My suggestions:

 - **Always** explain how to test it (unless it's really obvious);

 - If applicable and necessary, explain what should be the correct behaviour;

 - Reference the issue that you are solving "Solves #1904";

 - Always update the "On Test" tag ( this means that you should also remove it when the sprint is reseted);

 - Would be good to only add the tag when it's actually on test or comment "On test in 40min";

 - Call Michael and me in a comment for PO Approved;

 - Assign people for Code review;

 - Call people in a comment when you need help (explaining the problem) and one person auto-assign to help with the PR;

 - Same if you go for Holidays or get sick – Explain the situation and call people in the PR or assign;

**Comment by menor** [comment]
I just need to copy/paste this and 💥, thanks a lot.

Instead of calling Michael or you, they should assign you though.

**Comment by menor** [comment]
There was already [this](https://github.com/resmio/git-along/blob/master/pull-requests.md) for PR there, sorry. I will add your suggestions there though.
I guess I need to consolidate everything into one big readme, cause I completely forgot about this too.

**Comment by menor** [comment]
closed by #36
