### ISSUE TITLE
PR description/review

### ISSUE THREAD

**Issue by jessicalins** [resmio/git-along#4]
This issue is to discuss how can we organize better our process for submit pull requests. 2 things that I think that would be nice to organize better is the way that we submit a PR and our PR review process. Some ideas for this:

- When create a new PR, we could attach labels to it, to better identification. So, if I'm creating a backend PR, I can use for example the labels 'Backend' and 'Backend Refactoring'. Also, a short description explaining what this PR does, so the other people can have a better understanding of the code. I saw this in some link that @menor  send one time on HipChat, now I'm not finding it anymore :(

- To a better PR review process, we could merge a PR only if it has at least 2 reviews, for example. When we create a PR and it is finished, we can mention the people that could review it. 

What do you think?

**Comment by menor** [comment]
Agree great idea, what about having 3 labels:
- `Backend_Review`
- `Frontend_Review`
- `Product_Review`

And then another 3:
- `Backend_Reviewed`
- `Frontend_Reviewed`
- `Product_Reviewed`

We can make them in red tones and green tones, to make it look nicer, if we see a redish label there it can not be merged. a person can also go the issues on his/her spare moments, filter by one of the redish labels and see if anything needs to be reviewwed in his/her side.

**Comment by JanNash** [comment]
Also, to easily differentiate between labels meant for PRs and labels meant for issues, we might make the labels for issues all lowercase and the labels for PRs with every word capitalized

**Comment by ihucos** [comment]
I also think that the way we are doing it right now is not ideal. But I think its more about people (me included, all of us) just dedicating more time to pull requests than changing the way we use our tools. I have the feeling that for a smaller team we already have enough bureaucracy, what we need is just to adapt the way we work, for example pushing each other to review pull requests.

I would also suggest that if one person find it responsible he can just merge his own pull request or in some occasions push directly to master.

**Comment by menor** [comment]
You're right it's also about people @ihucos and some people don't like being pushed this is not about adding more bureaucracy it's about making the one we have now work better. The easier it is for me to filter the PR I need to check, the more often I will do it, and the less time I'll waste doing it.

I can not agree about merging our own pull requests and pushing to master, sorry.

**Comment by ihucos** [comment]
I have my opinion but will go with consensus.

**Comment by menor** [comment]
I will also go with consensus, so it's good that you express your opinion, maybe more people thinks like you.

Problem for me it's that right now we don't have a procedure about all this and this forces us to have to be on top of things. I hate processes and bureaucracy (and also typing the word bureaucracy) as much as you do, believe me. I even was in a punk rock band in 'the good old days'

**Comment by ihucos** [comment]
> I even was in a punk rock band in 'the good old days'
When and why did you quit?

Yeah... I mean lets try it out, maybe I'll like it.

**Comment by menor** [comment]
> I even was in a punk rock band in 'the good old days'
When and why did you quit?  

They kicked me out two years ago because I was adding too much bureaucracy.


@fabiennepimenta says this on Hipchat:
![image](https://cloud.githubusercontent.com/assets/1360794/18500463/ec037d0c-7a47-11e6-9046-45fff64c747e.png)

I'm going to create an issue so we can put the labels we need there
