### ISSUE TITLE
Define Label categories

### ISSUE THREAD

**Issue by menor** [resmio/git-along#7]
We have patterns like:

- Team: Backend, Frontend...
- Type:  bug, feature, enhancement
- Subject: bookings, dashboard, widget, admin ...
- Workflow: Blocked, code review needed, ...
- Size: x-small, small, ...
- Priority: p1, p2, and p3

If we identify the patterns we can then color code them by type like they do at [Robin](https://robinpowered.com/blog/best-practice-system-for-organizing-and-tagging-github-issues/) although in my opinion they have too many labels

Edited to add size and priority groups

**Comment by mmarder** [comment]
I guess we also have the size tags.

x-small - x-large
