### ISSUE TITLE
Define labels for category: domain

### ISSUE THREAD

**Issue by menor** [resmio/git-along#8]
Domain labels specify what domain an issue belongs to. Assigning a domain label makes sure issues get the attention of the appropriate people. We capitalize them so they appear first. Proposed color is `#66CDAA` (Medium Aquamarine)

Labels:
- `Backend`: Covers everything that doesn't fall under the responsibility of one of the others teams
- `Documentation`: Covers everything related to writing documentations.
- `Frontend`: Covers everything related to the way resmio behaves (and looks) in the browser.
- `Operations`: Covers everything related to operational stuff (deploys, merges, renewing SSL certificates, upgrading CloudAMQP, ...)
- `UX`: Issues for the UX team. Covers new or existing functionality that needs a design proposal.

Edited to change from CI to Operations

**Comment by JannKleen** [comment]
Maybe use ```Operations``` instead of ```CI``` and also use the label for all other operational stuff (renewing SSL certificates, upgrading CloudAMQP, etc.)

**Comment by menor** [comment]
![image](https://cloud.githubusercontent.com/assets/1360794/18634276/8fcf6392-7e80-11e6-91a1-c2c68575fcad.png)
